corncyc:
  source: 'https://ftp.maizegdb.org/MaizeGDB/FTP/MetabolicResources/CornCyc_install_files/CornCyc_8.0/corncyc8.0.tar.gz'
  dir:  '/ref/zea/corncyc/8.0/data'
  pathways_col:   "pathways.col"
  genes_col:     "genes.col"
  enzymes_col:   "enzymes.col"
  proteins_dat:  "proteins.dat"
  reactions_dat: "reactions.dat"
  genes_dat:     "genes.dat"
#KEGG:
ref:
  xref: "/ref/zea/gene_model_xref_v3.txt"
output:
  dir:   '/Volumes/GoogleDrive/My Drive/repos/pglipid/extdata/output'
  PBE:
  PCAdapt:
